blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView

app_name="blog"

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('create/', BlogCreateView.as_view(), name="create"),
    path('<int:pk>/', BlogDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name="update"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', HomeView.as_view(), name='home'),

    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from turtle import title
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField()

    def __str__(self):
        return self.title

blog/forms.py
from dataclasses import fields
from django import forms

from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','content')

blog/views.py
from turtle import title
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import View, UpdateView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

# Create your views here.
class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts':posts
        }
        return render(request, 'blog/index.html', context)

class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        formPostCreate = PostCreateForm()
        
        context = {
            'formPostCreate':formPostCreate
        }

        return render(request,'blog/create.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            formPostCreate = PostCreateForm(request.POST)
            if formPostCreate.is_valid():
                title = formPostCreate.cleaned_data.get('title')
                content = formPostCreate.cleaned_data.get('content')

                p, created = Post.objects.get_or_create(title = title, content = content)
                p.save()

                return redirect('blog:home')

        context = {
            'formPostCreate':formPostCreate
        }

        return render(request,'blog/create.html', context)

class BlogDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk = pk)
        context = {
            'post':post
        }
        return render(request, 'blog/detail.html', context)

class BlogUpdateView(UpdateView):
    model = Post
    fields = ['title', 'content']
    template_name = 'blog/update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs = {'pk':pk})

core/views.py
from math import degrees
from django.views.generic import View
from django.shortcuts import render, redirect

class HomeView(View):
    def get(self, request, *args, **kwargs):

        context = {
            
        }
        return render(request, 'index.html', context)

templates/blog/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    <p>
        Puedes crear un artículo
    </p>

    <form method="POST">
        {% csrf_token %}
        title <br> {{formPostCreate.title}} <br>
        content <br> {{formPostCreate.content}} <br>
        <button type="submit">Crear</button>
    </form>
    <br>
    <a href="{% url 'blog:home' %}"><<< Regresar</a>
</body>
</html>

templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    <h1>{{post.title}}</h1>
    <hr>
    <p>Descripción: {{post.content}}</p>
    <a href="{% url 'blog:home' %}"><<< Regresar</a>
</body>
</html>

templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    <p>
        Este es mi blog
    </p>
    <a href="{% url 'home' %}"><<< Regresar</a>
    <a href="{% url 'blog:create' %}">Crear >>></a>

    <br>

    {% for post in posts %}
        <p>Título: {{post.title}}</p>
        <a href="{% url 'blog:detail' post.id %}">Leer</a>
        <a href="{% url 'blog:update' post.id %}">Actualizar</a>
        <hr>
    {% endfor %}
</body>
</html>

templates/blog/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    <p>
        Puedes actualizar un artículo
    </p>

    <form method="POST">
        {% csrf_token %}
        title <br> {{form.title}} <br>
        content <br> {{form.content}} <br>
        <button type="submit">Actualizar</button>
    </form>
    <br>
    <a href="{% url 'blog:home' %}"><<< Regresar</a>
</body>
</html>

templates/index.html
Hola visita mi blog <a href="{% url 'blog:home' %}">aquí</a>